sudo: required
services:
  - docker

before_install:
  - docker build -t rishi/react-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true rishi/react-cicd npm run test

deploy:
  provider: heroku
  region: "United States"
  api_key:
    secure: "this-is-my-api_key"
  app: "docker-react-ci"
